# Generated by Django 2.2.10 on 2020-09-11 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FACE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('gender', models.BooleanField()),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(7)])),
            ],
        ),
        migrations.CreateModel(
            name='PERSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('in_out', models.BooleanField()),
            ],
        ),
    ]
