# Generated by Django 2.2.10 on 2020-09-12 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200912_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='person',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
