# Generated by Django 2.2.10 on 2020-09-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200913_0645'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='face',
            table='FACE',
        ),
        migrations.AlterModelTable(
            name='person',
            table='PERSON',
        ),
    ]
