# Generated by Django 2.2.10 on 2020-09-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200913_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_opt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('hour', models.CharField(choices=[('9', '09:00 - 10:00'), ('10', '10:00 - 11:00'), ('11', '11:00 - 12:00'), ('12', '12:00 - 13:00'), ('13', '13:00 - 14:00'), ('14', '14:00 - 15:00'), ('15', '15:00 - 16:00'), ('16', '16:00 - 17:00'), ('17', '17:00 - 18:00'), ('18', '18:00 - 19:00'), ('19', '19:00 - 20:00')], max_length=100)),
            ],
        ),
    ]
